### ISSUE TITLE
Reservar e planejar Mozillagram para tarefas de marketing global

### ISSUE THREAD

**Issue by barrosgg** [rust-br/2018-roadshow#28]
Tarefa: Reservar Mozillagram entre os dias 1-4 de fevereiro de 2018 e criar um planejamento de publicações para cada dia onde podemos monitorar as redes sociais e Telegram com a hashtag para obter imagens em tempo real e publicar.
Mentor: @barrosgeraldo

**Comment by barrosgg** [comment]
@cynthiapereira ou @thiagopolicena, vocês gostariam de pegar essa tarefa?

**Comment by cpswsg** [comment]
@barrosgeraldo precisamos identificar quem é a pessoa responsável pelo Mozillagram agora. A Sierra não gerencia mais as comunidades.

**Comment by barrosgg** [comment]
@cynthiapereira você quer contactar alguém que você tem em mente? Não sei por onde começar.

**Comment by cpswsg** [comment]
@barrosgeraldo Na próxima semana começo os trabalhos pode deixar essa task comigo.

**Comment by cpswsg** [comment]
Falei com Sierra, ela ainda é responsável por esse projeto (MozillaGram). Ela solicitou que eu entre em contato no dia 31 de janeiro para passar todos os dados.

Edit: Foi solicitado o periodo de 1 a 4 de Fevereiro.

**Comment by barrosgg** [comment]
Feito.
