### ISSUE TITLE
Adicionar oficinas ao calendário oficial de eventos da comunidade Rust

### ISSUE THREAD

**Issue by barrosgg** [rust-br/2018-roadshow#29]
Tarefa: Adicionar todas as [oficinas planejadas](https://rust-br.github.io/2018-roadshow/) ao [calendário oficial de eventos da comunidade Rust](https://calendar.google.com/calendar/embed?src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com&ctz=America%2FSao_Paulo).
Mentor: @barrosgeraldo

**Comment by leoyvens** [comment]
Tenho acesso ao calendário (é só pedir para ter), mas precisamos de dias e horários exatos para isso, creio eu.

**Comment by barrosgg** [comment]
Isso mesmo precisa dos dias exatos, essa issue está aqui para não esquecer de adicionar todos lá no calendário também. Ao adicionar os eventos ao calendário temos que ter em mente uma forma de padronizar, aqui está minha proposta:
Title: Dive Into Rust workshop @ nome do lugar
Color: Verde (para facilitar localizar os eventos do roadshow)
Guest: Adicionar o email do mobilizador e dar permissão que ele edite o evento específico, assim se tiver alterações, o próprio mobilizador pode fazer as alterações diretamente.

Certo? Vou atribuir a issue a você @leodasvacas para cuidar disso quando estiver tudo planejado no site do roadshow.

**Comment by barrosgg** [comment]
Feito.
