### ISSUE TITLE
Leandro Ferreira - Belo Horizonte-MG

### ISSUE THREAD

**Issue by leandromferreira** [rust-br/2018-roadshow#30]

**Comment by barrosgg** [comment]
Oi Leandro, por favor, [copie o conteúdo desse template](https://raw.githubusercontent.com/rust-br/2018-roadshow/master/ISSUE_TEMPLATE_INSCRICOES.md), cole na caixa de texto aqui da issue, preencha com as suas informações e envie para completar a sua inscrição.

**Comment by barrosgg** [comment]
Oi @leandromferreira, [conecte-se com os mobilizadores de Belo Horizonte](https://github.com/rust-br/2018-roadshow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Amobilizador+Belo+Horizonte) para fomentar as atividades em BH e região.
