### ISSUE TITLE
Maitê Balhester - São Paulo-SP

### ISSUE THREAD

**Issue by maiteb** [rust-br/2018-roadshow#33]
Hey, eu quero ser mobilizador Rust na minha região! Aqui está a minha inscrição:

**[ Nome e sobrenome ]** *Maitê Balhester*

**[ GitHub ]** *@maiteb*

**[ Twitter ]** *https://twitter.com/mbalhester*

**[ Cidade e Estado ]** *São Paulo - SP*

**[ Organização ]** *Thoughtworks*

**[ Tamanho de camiseta ]** *P*

**[ INFORMAÇÕES ADICIONAIS ]**

1. *Nós usaremos o seu e-mail vinculado ao GitHub para comunicação privada, se você deseja que o nosso time fale com você usando outro endereço de e-mail, adicione o endereço de e-mail abaixo desta mensagem.*

2. *Ao inscrever-se você concorda com nosso [código de conduta](https://github.com/rust-br/2018-roadshow/blob/master/CODE_OF_CONDUCT.md) a fim de nos ajudar a criar uma experiência segura e positiva para todos em todas as atividades dessa iniciativa.*

> _*Após enviar sua inscrição, aguarde um membro do time dar boas vindas e os próximos passos.*_

**Comment by barrosgg** [comment]
Oi @maiteb! Obrigado por juntar-se a nós!

Os treinamentos para mobilizadores já aconteceram, mas foram gravados e você pode assistir para entender melhor a nossa estratégia e as oficinas de Rust. 

> **[Chamada do projeto](https://github.com/rust-br/2018-roadshow/tree/master/recursos/chamada_de_treinamento_do_facilitador#chamada-do-projeto)**
> **Responsável:** @barrosgeraldo
> **Duração**: 1h15m
> **Data e hora**: Quinta, 21 de dezembro, 18h00min-19h30min BRST | Adicione ao [Google Agenda](https://calendar.google.com/event?action=TEMPLATE&tmeid=NHQxczl2OHIzOGxkYm9nN2E4bThxbXMxMmMgZ2VyYWxkb2JhcnJvc0Btb3ppbGxhYnIub3Jn&tmsrc=geraldobarros%40mozillabr.org) | [Doodle](https://doodle.com/poll/95ndedr79xe86sn2)
> **Onde**: [*Hangouts*](https://hangouts.google.com/hangouts/_/m32diiqgpvbxxmyr2l4fsxlykue) ou [*YouTube Ao Vivo*](http://youtu.be/4rlxB0_HD_I)
> **Notas**: [*Etherpad*](https://public.etherpad-mozilla.org/p/2018rustroadshowbrasil)
> 
> **[Chamada técnica](chamada_de_treinamento_do_facilitador/README.md#chamada-técnica)**
> **Responsável:** @leodasvacas
> **Duração**: 1h15m
> **Data e hora**: Quinta, 22 de dezembro, 18h00min-19h30min BRST | Adicione ao [Google Agenda](https://calendar.google.com/event?action=TEMPLATE&tmeid=Mm5jZm92ZzdsbG80bDBodmgzaWw4aGJwYXAgZ2VyYWxkb2JhcnJvc0Btb3ppbGxhYnIub3Jn&tmsrc=geraldobarros%40mozillabr.org) | [Doodle](https://doodle.com/poll/95ndedr79xe86sn2)
> **Onde**: [*Hangouts*](https://hangouts.google.com/hangouts/_/nelimixd6nc3baftrhprdhxxeue) ou [*YouTube Ao Vivo*](http://youtu.be/1jF3cI6aFJI)
> **Notas**: [*Etherpad*](https://public.etherpad-mozilla.org/p/2018rustroadshowbrasil)
> 
> 

Minha recomendação a partir de agora é você juntar-se a equipe de São Paulo para entrar na organização das atividades de Rust em planejamento, certo? Você pode falar diretamente com a galera nas issues #10 #16 #17 

Nós estamos preparando um blog post para anunciar os mobilizadores que fazem parte do projeto, então para isso nós precisamos da sua biografia e foto, você pode encaminhar para o Thiago que fará o blog post no e-mail: thiagopolicena@mozillabr.org.

Mantenha nos informado aqui se você precisa de suporte adicional. Thanks. :)

**Comment by barrosgg** [comment]
@maiteb, você usa Telegram? Nós temos um grupo de mobilizadores lá para troca rápida de informações e apoio, se desejar entrar no grupo me envie uma mensagem, meu usuário é _geraldobarros_. Abraços.

**Comment by thiagopolicena** [comment]
Olá SuperHero!!!

Está chegando o Rust Roadshow e necessitamos que finalize alguns itens para que possamos dar continuidade ao nosso planejamento, segue abaixo a relação:

- Finalizar a organização do workshop até domingo(21/01/2017);
- Após finalizar a organização dos workshops, enviar o planejamento da oficina na issue e solicitar swag/brindes e orçamento para o e-mail rust@mozillabr.org;

Qualquer dúvida estamos a disposição.

Keep Rocking :)

**Comment by cpswsg** [comment]
Olá @maiteb,

Muito obrigada pelo seu interesse em fazer parte do [Rust Roadshow Brasil 2018](https://github.com/rust-br/2018-roadshow#rust-roadshow-brasil-2018)! Foi motivador ver tantas pessoas como você interessadas em promover o Rust em mais localidades em nosso país.

Contudo, por algum motivo você não concluiu a sua participação nesta campanha comunitária e nós gostaríamos de saber como podemos melhorar para que no futuro você possa participar plenamente.

Por favor, não deixe de [**preencher este formulário rápido e anônimo**](https://goo.gl/forms/kEHNdj1vKodnomhd2). Ele nos ajudará a aprimorar nossas campanhas e a proporcionar uma melhor experiência a todos. 

Obrigada,

Cynthia Pereira
Em nome do time do Rust Roadshow Brasil 2018
