### ISSUE TITLE
Alexandra da Silva Pereira  -  Belo Horizonte-MG

### ISSUE THREAD

**Issue by alexandrasp** [rust-br/2018-roadshow#35]
**[ Nome e sobrenome ]** Alexandra da Silva Pereira

**[ Perfil no Mozillian.org ou Rustaceans.org ]** https://mozillians.org/en-US/u/alesilva241/

**[ GitHub ]** @alexandrasp

**[ Telegram ]** http://t.me/alexandrasp

**[ Twitter ]** https://twitter.com/alex_andrasp

**[ Outros links ]** https://alexandrasp.github.io/

**[ Cidade e Estado ]** Belo Horizonte - MG

**[ Tamanho de camiseta ]** M ou Fitted G.

**Comment by barrosgg** [comment]
Certificado digital enviado.
