### ISSUE TITLE
Émylle Andressa - Feira de Santana BA

### ISSUE THREAD

**Issue by ghost** [rust-br/2018-roadshow#36]
Olá!! O que preciso fazer para me tornar uma mobilizadora?

**Comment by barrosgg** [comment]
Oi Émylle,

Infelizmente as inscrições encerraram! :(

Orientações de como organizar uma oficina de Rust: https://github.com/rust-br/2018-roadshow/blob/master/CONTRIBUTING.md#oficina-de-rust

Dúvidas? Envie um e-mail para rust@mozillabr.org.
