### ISSUE TITLE
Jucélio Jair Silva -  São José-SC

### ISSUE THREAD

**Issue by celioware** [rust-br/2018-roadshow#4]
> _*Se você não se sente confortável em ter suas informações públicas aqui, lamentamos o inconveniente, isto faz parte dos nossos esforços em construir um projeto transparente, aberto e justo para todos, não se preocupe porque nós somos capazes de receber sua inscrição por e-mail via rust@mozillabr.org.*_

Hey, eu quero ser mobilizador Rust na minha região! Aqui está a minha inscrição:

**[ Nome e sobrenome ]** *Jucélio Jair Silva*

**[ Perfil no Mozillian.org ou Rustaceans.org ]** *https://mozillians.org/en-US/u/skalldihor/*

**[ GitHub ]** *@Skalldihor*

**[ Telegram ]** *@Skalldihor*

**[ Twitter ]** *https://twitter.com/@skalldihor*

**[ website ]** *https://skalldihor.github.io*

**[ Cidade e Estado ]** *São José-SC*

**[ Organização ]** *Rust Floripa*

**[ Tamanho de camiseta ]** *GG*

**[ INFORMAÇÕES ADICIONAIS ]**

1. *Nós usaremos o seu e-mail vinculado ao GitHub para comunicação privada, se você deseja que o nosso time fale com você usando outro endereço de e-mail, adicione o endereço de e-mail abaixo desta mensagem.*

2. *Ao inscrever-se você concorda com nosso [código de conduta](https://github.com/rust-br/2018-roadshow/blob/master/CODE_OF_CONDUCT.md) a fim de nos ajudar a criar uma experiência segura e positiva para todos em todas as atividades dessa iniciativa.*

> _*Após enviar sua inscrição, aguarde um membro do time dar boas vindas e os próximos passos.*_

**Comment by barrosgg** [comment]
Oi Jucélio,

![Alt Text](https://media.giphy.com/media/l4JyOCNEfXvVYEqB2/giphy.gif)

**Seja bem vindo(a) ao Rust Roadshow Brasil 2018!**

Agora você está dentro do projeto e nós usaremos essa issue para acompanhar o seu progresso e do seu time, não esqueça de revisar cuidadosamente o [seu papel, requisitos e outras informações relevantes disponibilizadas no guia de contribuidores antes de continuar](https://github.com/rust-br/2018-roadshow/blob/master/CONTRIBUTING.md#oficina-de-rust).

**O próximo passo é participar da primeira chamada** — eu sei que você tem muitas dúvidas sobre como funcionará todo o Roadshow e também quer conhecer todo o time e seus outros colegas mobilizadores que também estão no projeto, **então essa será a hora**, [marque os seus dias e horários disponíveis para a nossa primeira chamada que acontecerá na próxima semana no Doodle](https://doodle.com/poll/95ndedr79xe86sn2), **encerrarei a pesquisa no Doodle na segunda a qualquer horário, então certifique-se de fazer isso antes de segunda**.

_E se tiver dúvidas adicionais, você pode perguntar aqui mesmo na issue, ou [fale com nosso time](https://github.com/rust-br/2018-roadshow#contato) a qualquer momento._

Abraços e até semana que vem,
Geraldo Barros
:sparkles: :star: :star2: :dizzy: :boom: :collision:

**Comment by thiagopolicena** [comment]
Hi Jucélio!
Estamos preparando um belo Blog Post contando um pouco sobre os nossos **Super-Heróis** da Comunidade Rust e gostaria que me enviasse alguns dados:
**Nome Completo**
**Foto 250x250px**
**Biografia**

**Obs.:** Todos esses dados deverão ser encaminhados para o e-mail: **thiagopolicena@mozillabr.org**

**PRAZO: 22/12/2017**

Ab[]s.

**Comment by barrosgg** [comment]
Oi,

Obrigado por participar da nossa primeira chamada de treinamento, se não foi possível participar ao vivo, lembre-se que a mesma está disponível no [YouTube](https://youtu.be/4rlxB0_HD_I?t=746). Não esqueça da [chamada técnica manhã](https://github.com/rust-br/2018-roadshow/tree/master/recursos/chamada_de_treinamento_do_facilitador#chamada-t%C3%A9cnica). :D

Aqui tem algumas das tarefas para você começar a se preparar e organizar sua oficina local e compartilhar conosco.

### Lista de tarefas

- [ ] Ler o [Rust Brazil Mobilizers’ Handbook](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook)
- [ ] Organizar [logística](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook#log%C3%ADstica)
- [ ] Estratégia de [marketing para divulgar](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook#marketing)
- [ ] Reportar como foi a [oficina](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook#reportando)

### Sua oficina de Rust

 - Cidade/Estado:
 - Local (nome, endereço):
 - Data & Hora:
 - Link de inscrições:
  - Quantidade de participantes esperados:
 - Fuso horário:

**Assim que você tiver todos os dados você pode compartilhar conosco comentando aqui na issue**

### Lista de verificação

- [ ] Primeira chamada de treinamento (iniciativa, não técnica)
- [ ] Segunda chamada de treinamento (Rust, técnica)
- [x] Página de evento no site do programa [Mozilla Reps](https://reps.mozilla.org)
- [ ] Evento no calendário da comunidade Rust
- [x] Evento listado no site do Rust Roadshow

** Essa é uma lista de verificação de nossas tarefas (time do projeto), não se preocupe, você não precisa completar nenhum desses itens.**

Abraços e até amanhã,
Geraldo Barros

**Comment by barrosgg** [comment]
Hey Mobilizadores! Obrigado por enviar sua biografia & foto para o nosso blog post!

Está pronto! Nós criamos duas versões, em Inglês e Português, fique a vontade para divulgar nas redes sociais, adicione a hashtag #Rust2018 e também use seu link direto:

https://mozillabr.org/2018/01/adicionando-super-herois-a-comunidade-rust/#jucelio-silva

Português: https://mozillabr.org/2018/01/adicionando-super-herois-a-comunidade-rust/
Inglês: https://mozillabr.org/2018/01/adding-superheroes-to-the-rust-brazilian-community/

**Comment by barrosgg** [comment]
Hey @Skalldihor, como vai a organização da oficina de Rust? Precisa de apoio em algo?

**Comment by barrosgg** [comment]
Ping

**Comment by thiagopolicena** [comment]
Olá SuperHero!!!

Está chegando o Rust Roadshow e necessitamos que finalize alguns itens para que possamos dar continuidade ao nosso planejamento, segue abaixo a relação:

- Finalizar a organização do workshop até domingo(21/01/2017);
- Após finalizar a organização dos workshops, enviar o planejamento da oficina na issue e solicitar swag/brindes e orçamento para o e-mail rust@mozillabr.org;

Qualquer dúvida estamos a disposição.

Keep Rocking :)

**Comment by celioware** [comment]
@barrosgeraldo desculpe a demora em responder. Estou organizando junto com o @cauebs preciso enviar os arquivos que ele enviou? estamos organizando juntos o mesmo evento.

@thiagopolicena Ok, iremos enviar em breve.

**Comment by barrosgg** [comment]
@Skalldihor, não lembro da necessidade de nenhum arquivo.

**Comment by barrosgg** [comment]
@Skalldihor, desculpe a confusão, agora marquei você na issue do Cauê, agora podemos rastrear o trabalho de vocês pela issue #24. 🎉

**Comment by thiagopolicena** [comment]
Olá SuperHero!!! 

Chegamos no fim do nosso Rust Roadshow Brasil e para fechar com sucesso teremos nossa Chamada Pós-Evento na **Quarta, 28 de fevereiro, 21h00min-22h00min BRT** com duração aproximada de **01 hora** conforme votação feita no[ Doodle](https://doodle.com/poll/e2xvz7er56z35gza), onde iremos tratar dos seguintes assuntos:

-    Bem-Vindos!
-    Histórico do projeto
-    Feedback
-    Próximos passos

Para maiores informações confiram [aqui](https://github.com/rust-br/2018-roadshow/blob/master/recursos/chamada_de_treinamento_do_facilitador/README.md#chamada-p%C3%B3s-evento).

Vejo você na reunião []'s
