### ISSUE TITLE
Inventário do estoque de swag restante e possíveis destinos

### ISSUE THREAD

**Issue by barrosgg** [rust-br/2018-roadshow#40]
**Tarefa:** Inventário do estoque de swag restante e definir possíveis destinos

**Comment by alexandrasp** [comment]
Tenho interesse em pulseiras e adesivos! hehehe Há posilibidade?

**Comment by barrosgg** [comment]
@alexandrasp, as pulseiras são enviadas pela Mozilla via [Mozilla Reps program](https://reps.mozilla.org), se você tem atividades e tem interesse há vários tipos de swag que podem ser solicitados via Reps, assim que eu tiver o inventário do swag eu compartilho aqui.

**Comment by barrosgg** [comment]
**Inventário de swags produzidos (restante)**

- 100 Rust logo buttons
- 3 Pacotes de 60 Stickers
- 3 Camisetas Rust Laranja GGG
- 1 Camiseta Rust Laranja GG
- 2 Camisetas Rust Laranja P

**Comment by barrosgg** [comment]
Swag restante será destinado a atividades de Rust que estejam próximas de Campinas e São Paulo, interessados podem nos contactar por e-mail: rust@mozillabr.org.
