### ISSUE TITLE
Agradecimentos

### ISSUE THREAD

**Issue by barrosgg** [rust-br/2018-roadshow#43]

**Comment by barrosgg** [comment]
Rascunho pronto: https://docs.google.com/document/d/1jpVonmLeStaUXHLObIqeXwv9hpKyzVqFIiyRAG1DJ7I/edit

**Comment by barrosgg** [comment]
Agradecimentos, doodle e formulário de feedback enviados para #organização-completada.

**Comment by cpswsg** [comment]
Agradecimentos e formulário de feedback enviado para os interessados.
