### ISSUE TITLE
Mário Idival - Natal-RN

### ISSUE THREAD

**Issue by marioidival** [rust-br/2018-roadshow#8]
Hey, eu quero ser mobilizador Rust na minha região! Aqui está a minha inscrição:

**[ Nome e sobrenome ]** *Mário Idival.*

**[ Perfil no Mozillian.org ou Rustaceans.org ]** *https://www.rustaceans.org/marioidival*

**[ GitHub ]** *@marioidival*

**[ Telegram ]** *@marioidival*

**[ Twitter ]** *https://twitter.com/@marioidival*

**[ Cidade e Estado ]** *Natal - RN*

**[ Organização ]** 

1. GruPy - RN
2. Nuveo

**[ Tamanho de camiseta ]** *M*

**[ INFORMAÇÕES ADICIONAIS ]**

1. *Nós usaremos o seu e-mail vinculado ao GitHub para comunicação privada, se você deseja que o nosso time fale com você usando outro endereço de e-mail, adicione o endereço de e-mail abaixo desta mensagem.*

2. *Ao inscrever-se você concorda com nosso [código de conduta](https://github.com/rust-br/2018-roadshow/blob/master/CODE_OF_CONDUCT.md) a fim de nos ajudar a criar uma experiência segura e positiva para todos em todas as atividades dessa iniciativa.*

> _*Após enviar sua inscrição, aguarde um membro do time dar boas vindas e os próximos passos.*_

**Comment by barrosgg** [comment]
Oi Mário,

![Alt Text](https://media.giphy.com/media/l4JyOCNEfXvVYEqB2/giphy.gif)

**Seja bem vindo(a) ao Rust Roadshow Brasil 2018!**

Agora você está dentro do projeto e nós usaremos essa issue para acompanhar o seu progresso e do seu time, não esqueça de revisar cuidadosamente o [seu papel, requisitos e outras informações relevantes disponibilizadas no guia de contribuidores antes de continuar](https://github.com/rust-br/2018-roadshow/blob/master/CONTRIBUTING.md#oficina-de-rust).

**O próximo passo é participar da primeira chamada** — eu sei que você tem muitas dúvidas sobre como funcionará todo o Roadshow e também quer conhecer todo o time e seus outros colegas mobilizadores que também estão no projeto, **então essa será a hora**, [marque os seus dias e horários disponíveis para a nossa primeira chamada que acontecerá na próxima semana no Doodle](https://doodle.com/poll/95ndedr79xe86sn2), **encerrarei a pesquisa no Doodle na segunda a qualquer horário, então certifique-se de fazer isso antes de segunda**.

_E se tiver dúvidas adicionais, você pode perguntar aqui mesmo na issue, ou [fale com nosso time](https://github.com/rust-br/2018-roadshow#contato) a qualquer momento._

Abraços e até semana que vem,
Geraldo Barros
:sparkles: :star: :star2: :dizzy: :boom: :collision:

**Comment by barrosgg** [comment]
Heey Mário,

Obrigado por adicionar seus dias e horários disponíveis no Doodle que já encerramos e temos os dias e horários definidos para ambas chamadas de treinamento do facilitador que são:

**[Chamada do projeto](https://github.com/rust-br/2018-roadshow/tree/master/recursos/chamada_de_treinamento_do_facilitador#chamada-do-projeto)**
**Responsável:** @barrosgeraldo
**Duração**: 1h15m
**Data e hora**: Quinta, 21 de dezembro, 18h00min-19h30min BRST | Adicione ao [Google Agenda](https://calendar.google.com/event?action=TEMPLATE&tmeid=NHQxczl2OHIzOGxkYm9nN2E4bThxbXMxMmMgZ2VyYWxkb2JhcnJvc0Btb3ppbGxhYnIub3Jn&tmsrc=geraldobarros%40mozillabr.org) | [Doodle](https://doodle.com/poll/95ndedr79xe86sn2)
**Onde**: [*Hangouts*](https://hangouts.google.com/hangouts/_/m32diiqgpvbxxmyr2l4fsxlykue) ou [*YouTube Ao Vivo*](http://youtu.be/4rlxB0_HD_I)
**Notas**: [*Etherpad*](https://public.etherpad-mozilla.org/p/2018rustroadshowbrasil)

**[Chamada técnica](chamada_de_treinamento_do_facilitador/README.md#chamada-técnica)**
**Responsável:** @leodasvacas
**Duração**: 1h15m
**Data e hora**: Quinta, 22 de dezembro, 18h00min-19h30min BRST | Adicione ao [Google Agenda](https://calendar.google.com/event?action=TEMPLATE&tmeid=Mm5jZm92ZzdsbG80bDBodmgzaWw4aGJwYXAgZ2VyYWxkb2JhcnJvc0Btb3ppbGxhYnIub3Jn&tmsrc=geraldobarros%40mozillabr.org) | [Doodle](https://doodle.com/poll/95ndedr79xe86sn2)
**Onde**: [*Hangouts*](https://hangouts.google.com/hangouts/_/nelimixd6nc3baftrhprdhxxeue) ou [*YouTube Ao Vivo*](http://youtu.be/1jF3cI6aFJI)
**Notas**: [*Etherpad*](https://public.etherpad-mozilla.org/p/2018rustroadshowbrasil)

Durante a chamada **você pode participar ao vivo pelo link do Hangouts ou assistir pelo link do YouTube ao vivo, e acompanhar, adicionar perguntas e comentários nas notas da chamada**.

**As chamadas serão gravadas e disponibilizadas no YouTube como um vídeo não listado**, então você e a comunidade terá **acesso ao vídeo gravado pelo link do YouTube já disponibilizado acima**. 

> _**Se você não pode participar ao vivo nos horários das chamas de treinamento, sinta se a vontade para assistir a gravação da chamada pelo link do YouTube, ver as notas das chamadas, perguntas já respondidas e solicitar uma reunião adicional com o time se desejar.**_

Até logo,
Geraldo Barros
:punch: :metal:

**Comment by thiagopolicena** [comment]
Hi Mário!
Estamos preparando um belo Blog Post contando um pouco sobre os nossos **Super-Heróis** da Comunidade Rust e gostaria que me enviasse alguns dados:
**Nome Completo**
**Foto 250x250px**
**Biografia**

**Obs.:** Todos esses dados deverão ser encaminhados para o e-mail: **thiagopolicena@mozillabr.org**

**PRAZO: 22/12/2017**

Ab[]s.

**Comment by barrosgg** [comment]
Oi,

Obrigado por participar da nossa primeira chamada de treinamento, se não foi possível participar ao vivo, lembre-se que a mesma está disponível no [YouTube](https://youtu.be/4rlxB0_HD_I?t=746). Não esqueça da [chamada técnica manhã](https://github.com/rust-br/2018-roadshow/tree/master/recursos/chamada_de_treinamento_do_facilitador#chamada-t%C3%A9cnica). :D

Aqui tem algumas das tarefas para você começar a se preparar e organizar sua oficina local e compartilhar conosco.

### Lista de tarefas

- [x] Ler o [Rust Brazil Mobilizers’ Handbook](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook)
- [ ] Organizar [logística](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook#log%C3%ADstica)
- [ ] Estratégia de [marketing para divulgar](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook#marketing)
- [ ] Reportar como foi a [oficina](https://github.com/rust-br/2018-roadshow/tree/master/recursos/rust_brazil_mobilizers_handbook#reportando)

### Sua oficina de Rust

 - Cidade/Estado:
 - Local (nome, endereço):
 - Data & Hora:
 - Link de inscrições:
  - Quantidade de participantes esperados:
 - Fuso horário:

**Assim que você tiver todos os dados você pode compartilhar conosco comentando aqui na issue**

### Lista de verificação

- [ ] Primeira chamada de treinamento (iniciativa, não técnica)
- [ ] Segunda chamada de treinamento (Rust, técnica)
- [ ] Página de evento no site do programa [Mozilla Reps](https://reps.mozilla.org)
- [ ] Evento no calendário da comunidade Rust
- [ ] Evento listado no site do Rust Roadshow

** Essa é uma lista de verificação de nossas tarefas (time do projeto), não se preocupe, você não precisa completar nenhum desses itens.**

Abraços e até amanhã,
Geraldo Barros

**Comment by marioidival** [comment]
@thiagopolicena enviado

**Comment by barrosgg** [comment]
Hey Mobilizadores! Obrigado por enviar sua biografia & foto para o nosso blog post!

Está pronto! Nós criamos duas versões, em Inglês e Português, fique a vontade para divulgar nas redes sociais, adicione a hashtag #Rust2018 e também use seu link direto:

https://mozillabr.org/2018/01/adicionando-super-herois-a-comunidade-rust/#mario-idival

Português: https://mozillabr.org/2018/01/adicionando-super-herois-a-comunidade-rust/
Inglês: https://mozillabr.org/2018/01/adding-superheroes-to-the-rust-brazilian-community/

**Comment by barrosgg** [comment]
Hey @marioidival, como vai a organização da oficina de Rust? Precisa de apoio em algo?

**Comment by thiagopolicena** [comment]
Olá SuperHero!!!

Está chegando o Rust Roadshow e necessitamos que finalize alguns itens para que possamos dar continuidade ao nosso planejamento, segue abaixo a relação:

- Finalizar a organização do workshop até domingo(21/01/2017);
- Após finalizar a organização dos workshops, enviar o planejamento da oficina na issue e solicitar swag/brindes e orçamento para o e-mail rust@mozillabr.org;

Qualquer dúvida estamos a disposição.

Keep Rocking :)

**Comment by barrosgg** [comment]
@dlight e @marioidival, por favor, adicionem os detalhes da oficina:
 - Cidade/Estado:
 - Local (nome, endereço):
 - Data & Hora:
 - Link de inscrições:
  - Quantidade de participantes esperados:
 - Fuso horário:

**Comment by marioidival** [comment]
@barrosgeraldo 

- Cidade/Estado: Natal/RN
- Local: Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte | Natal - Central    Avenida Senador Salgado Filho, 1559, Tirol.CEP 59015-000 
- Data & Hora: 17/02/2018, 13hs
- Link das inscrições: https://goo.gl/forms/g0bpd7DUpVvkJF4J2
- Quantidade de participantes esperados: 30
- Fuso horário: UTC/GMT -3

**Comment by barrosgg** [comment]
Mozilla Reps event page: https://reps.mozilla.org/e/dive-into-rust-ifrn/

**Comment by barrosgg** [comment]
Oi Mário,

No final do mês faremos uma chamada pós evento para receber feedback e discutir os próximos passos, então após sua oficina [deixe a sua opinião neste formulário](https://goo.gl/forms/CQurD8NxPb2bLanx1) e [marque seus horários disponíveis](https://doodle.com/poll/e2xvz7er56z35gza) para garantir que possamos acomodar todos em nossa reunião após o projeto. Por favor, faça isso **até dia 24  de fevereiro**.

Obrigado,

Geraldo Barros
Em nome do time do [Rust Roadshow Brasil 2018](https://github.com/rust-br/2018-roadshow#rust-roadshow-brasil-2018-)

**Comment by thiagopolicena** [comment]
Olá SuperHero!!! 

Chegamos no fim do nosso Rust Roadshow Brasil e para fechar com sucesso teremos nossa Chamada Pós-Evento na **Quarta, 28 de fevereiro, 21h00min-22h00min BRT** com duração aproximada de **01 hora** conforme votação feita no[ Doodle](https://doodle.com/poll/e2xvz7er56z35gza), onde iremos tratar dos seguintes assuntos:

-    Bem-Vindos!
-    Histórico do projeto
-    Feedback
-    Próximos passos

Para maiores informações confiram [aqui](https://github.com/rust-br/2018-roadshow/blob/master/recursos/chamada_de_treinamento_do_facilitador/README.md#chamada-p%C3%B3s-evento).

Vejo você na reunião []'s
